services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    command: >
      bash -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master --port 7077 --webui-port 8080"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks: [sparknet]

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-1
    command: >
      bash -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077 --webui-port 8081"
    depends_on: [spark-master]
    ports:
      - "8081:8081"
    networks: [sparknet]

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-2
    command: >
      bash -c "$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077 --webui-port 8082"
    depends_on: [spark-master]
    ports:
      - "8082:8082"
    networks: [sparknet]

  spark-submit:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-submit
    volumes:
      - ./spark:/opt/spark-apps
    working_dir: /opt/spark-apps
    networks: [sparknet]

  postgres:
    image: postgres:15
    container_name: pg
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gamc
    ports:
      - "5432:5432"
    networks: [sparknet]

networks:
  sparknet:
    driver: bridge
